variable "region" {}
variable "project_name" {}
variable "vpc-cidr" {}
variable "public_subnet_1az_cidr" {}
variable "public_subnet_2az_cidr" {}
variable "private_app_subnet_1az_cidr" {}
variable "private_app_subnet_2az_cidr" {}
variable "private_data_subnet_1az_cidr" {}
variable "private_data_subnet_2az_cidr" {}